In [26]:
print("Hello, World!")
print("\nSubmitted By:\nName: Ayesh Ahmad\nCMS: 365966\nSection: BESE-12A")

Hello, World!

Submitted By:
Name: Ayesh Ahmad
CMS: 365966
Section: BESE-12A


In [ ]:
import numpy as np

a = np.array([1, 2, 3])   # Create a rank 1 array
print(type(a))            # Prints "<class 'numpy.ndarray'>"
print(a.shape)            # Prints "(3,)"
print(a[0], a[1], a[2])   # Prints "1 2 3"
a[0] = 5                  # Change an element of the array
print(a)                  # Prints "[5, 2, 3]"

b = np.array([[1,2,3],[4,5,6]])    # Create a rank 2 array
print(b.shape)                     # Prints "(2, 3)"
print(b[0, 0], b[0, 1], b[1, 0])   # Prints "1 2 4"

<class 'numpy.ndarray'>
(3,)
1 2 3
[5 2 3]
(2, 3)
1 2 4


In [ ]:
import numpy as np

a = np.zeros((2,2))   # Create an array of all zeros
print(a)              # Prints "[[ 0.  0.]
                      #          [ 0.  0.]]"
b = np.ones((1,2))    # Create an array of all ones
print(b)              # Prints "[[ 1.  1.]]"

c = np.full((2,2), 7)  # Create a constant array
print(c)               # Prints "[[ 7.  7.]
                       #          [ 7.  7.]]"
d = np.eye(2)         # Create a 2x2 identity matrix
print(d)              # Prints "[[ 1.  0.]
                      #          [ 0.  1.]]"
e = np.random.random((2,2))  # Create an array filled with random values
print(e)                     # Might print "[[ 0.91940167  0.08143941]
                             #               [ 0.68744134  0.87236687]]"

[[0. 0.]
 [0. 0.]]
[[1. 1.]]
[[7 7]
 [7 7]]
[[1. 0.]
 [0. 1.]]
[[0.35907008 0.49491372]
 [0.90907272 0.78483917]]


In [ ]:
import numpy as np

# Create the following rank 2 array with shape (3, 4)
# [[ 1  2  3  4]
#  [ 5  6  7  8]
#  [ 9 10 11 12]]
a = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])

# Use slicing to pull out the subarray consisting of the first 2 rows
# and columns 1 and 2; b is the following array of shape (2, 2):
# [[2 3]
#  [6 7]]
b = a[:2, 1:3]

# A slice of an array is a view into the same data, so modifying it
# will modify the original array.
print(a[0, 1])   # Prints "2"
b[0, 0] = 77     # b[0, 0] is the same piece of data as a[0, 1]
print(a[0, 1])   # Prints "77"

2
77


In [ ]:
import numpy as np

# Create the following rank 2 array with shape (3, 4)
# [[ 1  2  3  4]
#  [ 5  6  7  8]
#  [ 9 10 11 12]]
a = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])

# Two ways of accessing the data in the middle row of the array.
# Mixing integer indexing with slices yields an array of lower rank,
# while using only slices yields an array of the same rank as the
# original array:
row_r1 = a[1, :]    # Rank 1 view of the second row of a
row_r2 = a[1:2, :]  # Rank 2 view of the second row of a
print(row_r1, row_r1.shape)  # Prints "[5 6 7 8] (4,)"
print(row_r2, row_r2.shape)  # Prints "[[5 6 7 8]] (1, 4)"

# We can make the same distinction when accessing columns of an array:
col_r1 = a[:, 1]
col_r2 = a[:, 1:2]
print(col_r1, col_r1.shape)  # Prints "[ 2  6 10] (3,)"
print(col_r2, col_r2.shape)  # Prints "[[ 2]
                             #          [ 6]
                             #          [10]] (3, 1)"

[5 6 7 8] (4,)
[[5 6 7 8]] (1, 4)
[ 2  6 10] (3,)
[[ 2]
 [ 6]
 [10]] (3, 1)


In [ ]:
import numpy as np

a = np.array([[1,2], [3, 4], [5, 6]])

# An example of integer array indexing.
# The returned array will have shape (3,) and
print(a[[0, 1, 2], [0, 1, 0]])  # Prints "[1 4 5]"

# The above example of integer array indexing is equivalent to this:
print(np.array([a[0, 0], a[1, 1], a[2, 0]]))  # Prints "[1 4 5]"

# When using integer array indexing, you can reuse the same
# element from the source array:
print(a[[0, 0], [1, 1]])  # Prints "[2 2]"

# Equivalent to the previous integer array indexing example
print(np.array([a[0, 1], a[0, 1]]))  # Prints "[2 2]"

[1 4 5]
[1 4 5]
[2 2]
[2 2]


In [ ]:
import numpy as np

# Create a new array from which we will select elements
a = np.array([[1,2,3], [4,5,6], [7,8,9], [10, 11, 12]])

print(a)  # prints "array([[ 1,  2,  3],
          #                [ 4,  5,  6],
          #                [ 7,  8,  9],
          #                [10, 11, 12]])"

# Create an array of indices
b = np.array([0, 2, 0, 1])

# Select one element from each row of a using the indices in b
print(a[np.arange(4), b])  # Prints "[ 1  6  7 11]"

# Mutate one element from each row of a using the indices in b
a[np.arange(4), b] += 10

print(a)  # prints "array([[11,  2,  3],
          #                [ 4,  5, 16],
          #                [17,  8,  9],
          #                [10, 21, 12]])

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
[ 1  6  7 11]
[[11  2  3]
 [ 4  5 16]
 [17  8  9]
 [10 21 12]]


In [ ]:
import numpy as np

a = np.array([[1,2], [3, 4], [5, 6]])

bool_idx = (a > 2)   # Find the elements of a that are bigger than 2;
                     # this returns a NumPy array of Booleans of the same
                     # shape as a, where each slot of bool_idx tells
                     # whether that element of a is > 2.

print(bool_idx)      # Prints "[[False False]
                     #          [ True  True]
                     #          [ True  True]]"

# We use boolean array indexing to construct a rank 1 array
# consisting of the elements of a corresponding to the True values
# of bool_idx
print(a[bool_idx])  # Prints "[3 4 5 6]"

# We can do all of the above in a single concise statement:
print(a[a > 2])     # Prints "[3 4 5 6]"

[[False False]
 [ True  True]
 [ True  True]]
[3 4 5 6]
[3 4 5 6]


In [ ]:
import numpy as np

x = np.array([1, 2])   # Let NumPy choose the datatype
print(x.dtype)         # Prints "int64"

x = np.array([1.0, 2.0])   # Let NumPy choose the datatype
print(x.dtype)             # Prints "float64"

x = np.array([1, 2], dtype=np.int64)   # Force a particular datatype
print(x.dtype)                         # Prints "int64"

int64
float64
int64


In [ ]:
import numpy as np

x = np.array([[1,2],[3,4]], dtype=np.float64)
y = np.array([[5,6],[7,8]], dtype=np.float64)

# Elementwise sum; both produce the array
# [[ 6.0  8.0]
#  [10.0 12.0]]
print(x + y)
print(np.add(x, y))

# Elementwise difference; both produce the array
# [[-4.0 -4.0]
#  [-4.0 -4.0]]
print(x - y)
print(np.subtract(x, y))

# Elementwise product; both produce the array
# [[ 5.0 12.0]
#  [21.0 32.0]]
print(x * y)
print(np.multiply(x, y))

# Elementwise division; both produce the array
# [[ 0.2         0.33333333]
#  [ 0.42857143  0.5       ]]
print(x / y)
print(np.divide(x, y))

# Elementwise square root; produces the array
# [[ 1.          1.41421356]
#  [ 1.73205081  2.        ]]
print(np.sqrt(x))

[[ 6.  8.]
 [10. 12.]]
[[ 6.  8.]
 [10. 12.]]
[[-4. -4.]
 [-4. -4.]]
[[-4. -4.]
 [-4. -4.]]
[[ 5. 12.]
 [21. 32.]]
[[ 5. 12.]
 [21. 32.]]
[[0.2        0.33333333]
 [0.42857143 0.5       ]]
[[0.2        0.33333333]
 [0.42857143 0.5       ]]
[[1.         1.41421356]
 [1.73205081 2.        ]]


In [ ]:
import numpy as np

x = np.array([[1,2],[3,4]])
y = np.array([[5,6],[7,8]])

v = np.array([9,10])
w = np.array([11, 12])

# Inner product of vectors; both produce 219
print(v.dot(w))
print(np.dot(v, w))

# Matrix / vector product; both produce the rank 1 array [29 67]
print(x.dot(v))
print(np.dot(x, v))

# Matrix / matrix product; both produce the rank 2 array
# [[19 22]
#  [43 50]]
print(x.dot(y))
print(np.dot(x, y))

219
219
[29 67]
[29 67]
[[19 22]
 [43 50]]
[[19 22]
 [43 50]]


In [ ]:
import numpy as np

x = np.array([[1,2],[3,4]])

print(np.sum(x))  # Compute sum of all elements; prints "10"
print(np.sum(x, axis=0))  # Compute sum of each column; prints "[4 6]"
print(np.sum(x, axis=1))  # Compute sum of each row; prints "[3 7]"

10
[4 6]
[3 7]


In [ ]:
import numpy as np

x = np.array([[1,2], [3,4]])
print(x)    # Prints "[[1 2]
            #          [3 4]]"
print(x.T)  # Prints "[[1 3]
            #          [2 4]]"

# Note that taking the transpose of a rank 1 array does nothing:
v = np.array([1,2,3])
print(v)    # Prints "[1 2 3]"
print(v.T)  # Prints "[1 2 3]"

[[1 2]
 [3 4]]
[[1 3]
 [2 4]]
[1 2 3]
[1 2 3]


In [ ]:
import numpy as np

# We will add the vector v to each row of the matrix x,
# storing the result in the matrix y
x = np.array([[1,2,3], [4,5,6], [7,8,9], [10, 11, 12]])
v = np.array([1, 0, 1])
y = np.empty_like(x)   # Create an empty matrix with the same shape as x

# Add the vector v to each row of the matrix x with an explicit loop
for i in range(4):
    y[i, :] = x[i, :] + v

# Now y is the following
# [[ 2  2  4]
#  [ 5  5  7]
#  [ 8  8 10]
#  [11 11 13]]
print(y)

[[ 2  2  4]
 [ 5  5  7]
 [ 8  8 10]
 [11 11 13]]


In [ ]:
import numpy as np

# We will add the vector v to each row of the matrix x,
# storing the result in the matrix y
x = np.array([[1,2,3], [4,5,6], [7,8,9], [10, 11, 12]])
v = np.array([1, 0, 1])
vv = np.tile(v, (4, 1))   # Stack 4 copies of v on top of each other
print(vv)                 # Prints "[[1 0 1]
                          #          [1 0 1]
                          #          [1 0 1]
                          #          [1 0 1]]"
y = x + vv  # Add x and vv elementwise
print(y)  # Prints "[[ 2  2  4
          #          [ 5  5  7]
          #          [ 8  8 10]
          #          [11 11 13]]"

[[1 0 1]
 [1 0 1]
 [1 0 1]
 [1 0 1]]
[[ 2  2  4]
 [ 5  5  7]
 [ 8  8 10]
 [11 11 13]]


In [ ]:
import numpy as np

# We will add the vector v to each row of the matrix x,
# storing the result in the matrix y
x = np.array([[1,2,3], [4,5,6], [7,8,9], [10, 11, 12]])
v = np.array([1, 0, 1])
y = x + v  # Add v to each row of x using broadcasting
print(y)  # Prints "[[ 2  2  4]
          #          [ 5  5  7]
          #          [ 8  8 10]
          #          [11 11 13]]"

[[ 2  2  4]
 [ 5  5  7]
 [ 8  8 10]
 [11 11 13]]


In [ ]:
import numpy as np

# Compute outer product of vectors
v = np.array([1,2,3])  # v has shape (3,)
w = np.array([4,5])    # w has shape (2,)
# To compute an outer product, we first reshape v to be a column
# vector of shape (3, 1); we can then broadcast it against w to yield
# an output of shape (3, 2), which is the outer product of v and w:
# [[ 4  5]
#  [ 8 10]
#  [12 15]]
print(np.reshape(v, (3, 1)) * w)

# Add a vector to each row of a matrix
x = np.array([[1,2,3], [4,5,6]])
# x has shape (2, 3) and v has shape (3,) so they broadcast to (2, 3),
# giving the following matrix:
# [[2 4 6]
#  [5 7 9]]
print(x + v)

# Add a vector to each column of a matrix
# x has shape (2, 3) and w has shape (2,).
# If we transpose x then it has shape (3, 2) and can be broadcast
# against w to yield a result of shape (3, 2); transposing this result
# yields the final result of shape (2, 3) which is the matrix x with
# the vector w added to each column. Gives the following matrix:
# [[ 5  6  7]
#  [ 9 10 11]]
print((x.T + w).T)
# Another solution is to reshape w to be a column vector of shape (2, 1);
# we can then broadcast it directly against x to produce the same
# output.
print(x + np.reshape(w, (2, 1)))

# Multiply a matrix by a constant:
# x has shape (2, 3). NumPy treats scalars as arrays of shape ();
# these can be broadcast together to shape (2, 3), producing the
# following array:
# [[ 2  4  6]
#  [ 8 10 12]]
print(x * 2)

[[ 4  5]
 [ 8 10]
 [12 15]]
[[2 4 6]
 [5 7 9]]
[[ 5  6  7]
 [ 9 10 11]]
[[ 5  6  7]
 [ 9 10 11]]
[[ 2  4  6]
 [ 8 10 12]]


In [13]:
# Assessment Exercise 6
import numpy as np

def array_to_vector(arr):
    """
    Convert a 3D NumPy array to a vector.
    """
    vector = arr.reshape(-1, 1)
    return vector

# Example usage:
array_3d = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])

vector = array_to_vector(array_3d)

print("Original array shape:", array_3d.shape)
print("Vector shape:", vector.shape)
print("Vector:")
print(vector)

Original array shape: (2, 2, 2)
Vector shape: (8, 1)
Vector:
[[1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]]


In [14]:
# Assessment Exercise 7
import numpy as np
# import math # Math library was used to develop part 'a' of this exercise and
              # was commented out in part 'b' after reasoning its invalid use.
def sigmoid(x):
    """
    Computes the sigmoid value of a real number.
    """
    sigmoid_value = 1 / (1 + np.exp(-x))
    return sigmoid_value

# Example usage:
x = np.array([1, 2, 3, 4, 5])
sigmoid = sigmoid(x)

print("Array: ", x)
print("Sigmoid Value: ", sigmoid)

Array:  [1 2 3 4 5]
Sigmoid Value:  [0.73105858 0.88079708 0.95257413 0.98201379 0.99330715]


In [15]:
# Assessment Exercise 8
import numpy as np

def softmax(matrix):
    """
    Computes the softmax function for each row of a matrix.
    """
    # Compute the exponential of each element of the matrix
    exp_matrix = np.exp(matrix)

    # Compute the sum of exponentials for each row
    sum_exp_matrix = np.sum(exp_matrix, axis=1, keepdims=True)

    # Compute softmax by dividing each element by the sum of exponentials for its row
    softmax_matrix = exp_matrix / sum_exp_matrix

    return softmax_matrix

# Example usage:
matrix = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])

softmax_matrix = softmax(matrix)

print("Original matrix:")
print(matrix)
print("Softmax matrix:")
print(softmax_matrix)

Original matrix:
[[1 2 3]
 [4 5 6]
 [7 8 9]]
Softmax matrix:
[[0.09003057 0.24472847 0.66524096]
 [0.09003057 0.24472847 0.66524096]
 [0.09003057 0.24472847 0.66524096]]


In [18]:
# Assessment Exercise 9
import numpy as np
import time

def custom_dot_product(vector1, vector2):
    """
    Computes the dot product of two vectors.
    """
    dot_product_value = sum(x * y for x, y in zip(vector1, vector2, strict=True))
    return dot_product_value

def np_dot_product(vector1, vector2):
    """
    Computes the dot product of two vectors using NumPy's np.dot() function.
    """
    dot_product_value = np.dot(vector1, vector2)
    return dot_product_value

# Example usage:
vector1 = list(range(1, 1000001))
vector2 = list(range(1, 1000001))

start_time = time.time()
result = custom_dot_product(vector1, vector2)
end_time = time.time()

print("Dot product result using custom function:\t ", result)
print("Time taken using custom function:\t\t ", end_time - start_time, " seconds")

start_time = time.time()
result = np_dot_product(np.array(vector1), np.array(vector2))
end_time = time.time()

print("\nDot product result using np.dot():\t\t ", result)
print("Time taken using np.dot():\t\t\t ", end_time - start_time, " seconds")

Dot product result using custom function:	  333333833333500000
Time taken using custom function:		  0.10598874092102051  seconds

Dot product result using np.dot():		  333333833333500000
Time taken using np.dot():			  0.1975560188293457  seconds


In [20]:
# Assessment Exercise 10
import numpy as np
import time

def custom_outer_product(vector1, vector2):
    """
    Computes the outer product of two vectors.
    """
    outer_product_result = [[x * y for y in vector2] for x in vector1]
    return outer_product_result

def np_outer_product(vector1, vector2):
    """
    Computes the outer product of two vectors using NumPy's np.outer() function.
    """
    outer_product_result = np.outer(vector1, vector2)
    return outer_product_result

# Example usage:
vector1 = [1, 2, 3]
vector2 = [4, 5, 6]

start_time = time.time()
result = custom_outer_product(vector1, vector2)
end_time = time.time()

print("Outer product result using custom function:\t ")
for row in result:
    print(row)

print("Time taken using custom function:\t\t ", end_time - start_time, "seconds")

start_time_np = time.time()
result_np = np_outer_product(vector1, vector2)
end_time_np = time.time()

print("\nOuter product result using np.outer():\t\t ")
print(result_np)

print("Time taken using np.outer():\t\t\t ", end_time_np - start_time_np, "seconds")


Outer product result using custom function:	 
[4, 5, 6]
[8, 10, 12]
[12, 15, 18]
Time taken using custom function:		  8.225440979003906e-05 seconds

Outer product result using np.outer():		 
[[ 4  5  6]
 [ 8 10 12]
 [12 15 18]]
Time taken using np.outer():			  0.0002300739288330078 seconds


In [21]:
# Assessment Exercise 11
import numpy as np
import time

def l1_loss_list(vector1, vector2):
    """
    Computes the L1 loss between two vectors using standard Python lists.
    """
    l1_loss = sum(abs(x - y) for x, y in zip(vector1, vector2))
    return l1_loss

def l1_loss_numpy(vector1, vector2):
    """
    Computes the L1 loss between two vectors using NumPy arrays.
    """
    vector1_np = np.array(vector1)
    vector2_np = np.array(vector2)
    l1_loss = np.sum(np.abs(vector1_np - vector2_np))
    return l1_loss

def l2_loss_list(vector1, vector2):
    """
    Computes the L1 loss between two vectors using standard Python lists.
    """
    l2_loss = sum((x - y) ** 2 for x, y in zip(vector1, vector2))
    return l2_loss

def l2_loss_numpy(vector1, vector2):
    """
    Computes the L1 loss between two vectors using NumPy arrays.
    """
    vector1_np = np.array(vector1)
    vector2_np = np.array(vector2)
    l2_loss = np.sum((vector1_np - vector2_np) ** 2)
    return l2_loss

# Example usage:
vector1 = [1, 2, 3, 4, 5]
vector2 = [2, 3, 4, 5, 6]

start_time = time.time()
l1_loss_standard = l1_loss_list(vector1, vector2)
end_time = time.time()
print("L1 loss using standard Python lists:", l1_loss_standard)
print("Time taken:\t\t ", end_time - start_time, "seconds")

start_time = time.time()
l1_loss_numpy = l1_loss_numpy(vector1, vector2)
end_time = time.time()
print("\nL1 loss using standard Python lists:", l1_loss_numpy)
print("Time taken:\t\t ", end_time - start_time, "seconds")

start_time = time.time()
l2_loss_standard = l2_loss_list(vector1, vector2)
end_time = time.time()
print("\nL2 loss using standard Python lists:", l2_loss_standard)
print("Time taken:\t\t ", end_time - start_time, "seconds")

start_time = time.time()
l2_loss_numpy = l2_loss_numpy(vector1, vector2)
end_time = time.time()
print("\nL2 loss using standard Python lists:", l2_loss_numpy)
print("Time taken:\t\t ", end_time - start_time, "seconds")

L1 loss using standard Python lists: 5
Time taken:		  0.0008480548858642578 seconds

L1 loss using standard Python lists: 5
Time taken:		  0.0002617835998535156 seconds

L2 loss using standard Python lists: 5
Time taken:		  0.00011920928955078125 seconds

L2 loss using standard Python lists: 5
Time taken:		  0.000141143798828125 seconds


In [22]:
# Assessment Exercise 12
import numpy as np

def matrix_addition(matrix1, matrix2):
    """
    Performs matrix addition using standard Python data structures.
    """
    if len(matrix1) != len(matrix2) or len(matrix1[0]) != len(matrix2[0]):
        raise ValueError("Matrices must have the same dimensions for addition")

    result = []
    for i in range(len(matrix1)):
        row = []
        for j in range(len(matrix1[0])):
            row.append(matrix1[i][j] + matrix2[i][j])
        result.append(row)
    return result

def matrix_addition_numpy(matrix1, matrix2):
    """
    Performs matrix addition using NumPy arrays.
    """
    if matrix1.shape != matrix2.shape:
        raise ValueError("Matrices must have the same dimensions for addition")

    result = matrix1 + matrix2
    return result

# Example usage:
matrix1 = [[1, 2, 3],
           [4, 5, 6],
           [7, 8, 9]]

matrix2 = [[9, 8, 7],
           [6, 5, 4],
           [3, 2, 1]]

result_standard = matrix_addition(matrix1, matrix2)
print("Matrix addition using standard Python data structures:")
for row in result_standard:
    print(row)

matrix1_np = np.array(matrix1)
matrix2_np = np.array(matrix2)
result_numpy = matrix_addition_numpy(matrix1_np, matrix2_np)
print("\nMatrix addition using NumPy arrays:")
print(result_numpy)


Matrix addition using standard Python data structures:
[10, 10, 10]
[10, 10, 10]
[10, 10, 10]

Matrix addition using NumPy arrays:
[[10 10 10]
 [10 10 10]
 [10 10 10]]


In [23]:
# Assessment Exercise 13
import numpy as np

def matrix_vector_multiplication(matrix, vector):
    """
    Performs matrix and vector multiplication using standard Python data structures.
    """
    if len(matrix[0]) != len(vector):
        raise ValueError("Matrix column count must match vector length for multiplication")

    result = []
    for row in matrix:
        row_sum = sum(row[i] * vector[i] for i in range(len(vector)))
        result.append(row_sum)
    return result

def matrix_vector_multiplication_numpy(matrix, vector):
    """
    Performs matrix and vector multiplication using NumPy arrays.
    """
    if matrix.shape[1] != len(vector):
        raise ValueError("Matrix column count must match vector length for multiplication")

    result = np.dot(matrix, vector)
    return result

# Example usage:
matrix = [[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]

vector = [1, 2, 3]

result_standard = matrix_vector_multiplication(matrix, vector)
print("Matrix and vector multiplication using standard Python data structures:")
print(result_standard)

matrix_np = np.array(matrix)
vector_np = np.array(vector)
result_numpy = matrix_vector_multiplication_numpy(matrix_np, vector_np)
print("\nMatrix and vector multiplication using NumPy arrays:")
print(result_numpy)


Matrix and vector multiplication using standard Python data structures:
[14, 32, 50]

Matrix and vector multiplication using NumPy arrays:
[14 32 50]


In [24]:
# Assessment Exercise 14
import numpy as np

def matrix_multiplication(matrix1, matrix2):
    """
    Performs matrix and matrix multiplication using standard Python data structures.
    """
    if len(matrix1[0]) != len(matrix2):
        raise ValueError("Matrix1 column count must match Matrix2 row count for multiplication")

    result = []
    for i in range(len(matrix1)):
        row = []
        for j in range(len(matrix2[0])):
            value = sum(matrix1[i][k] * matrix2[k][j] for k in range(len(matrix2)))
            row.append(value)
        result.append(row)
    return result

def matrix_multiplication_numpy(matrix1, matrix2):
    """
    Performs matrix and matrix multiplication using NumPy arrays.
    """
    if matrix1.shape[1] != matrix2.shape[0]:
        raise ValueError("Matrix1 column count must match Matrix2 row count for multiplication")

    result = np.dot(matrix1, matrix2)
    return result

# Example usage:
matrix1 = [[1, 2, 3],
           [4, 5, 6],
           [7, 8, 9]]

matrix2 = [[9, 8, 7],
           [6, 5, 4],
           [3, 2, 1]]

result_standard = matrix_multiplication(matrix1, matrix2)
print("Matrix and matrix multiplication using standard Python data structures:")
for row in result_standard:
    print(row)

matrix1_np = np.array(matrix1)
matrix2_np = np.array(matrix2)
result_numpy = matrix_multiplication_numpy(matrix1_np, matrix2_np)
print("\nMatrix and matrix multiplication using NumPy arrays:")
print(result_numpy)

Matrix and matrix multiplication using standard Python data structures:
[30, 24, 18]
[84, 69, 54]
[138, 114, 90]

Matrix and matrix multiplication using NumPy arrays:
[[ 30  24  18]
 [ 84  69  54]
 [138 114  90]]
